### ISSUE TITLE
Moving not intuive

### ISSUE THREAD

**Issue by benjaminkomen** [Sixish/Odyssey#13]
It took me some time to realize I can't move around the map using mouse dragging but had to use arrow keys instead. Which is ok, but some explanation would be nice. At the top or bottom a small textbox saying: "Use the arrow keys on your keyboard to move around."

**Comment by Sixish** [comment]
Uh, this project died with TibiaCast...

**Comment by benjaminkomen** [comment]
That is too bad :/
